ARG BASE=php

FROM composer:2.8.10 AS composer
FROM k8s.gcr.io/pause:3.10 AS pause

FROM ${BASE}

ARG DISTRO=debian
ARG SUITE
ARG VERSION

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=pause /pause /usr/local/bin/pause

ENV FPM_PM_MAX_CHILDREN=10 \
    FPM_PM_START_SERVERS=1 \
    FPM_PM_MIN_SPARE_SERVERS=1 \
    FPM_PM_MAX_SPARE_SERVERS=5

RUN --mount=type=bind,target=/build,source=./build \
    set -eux; \
    cd /build; \
    . ./build.sh; \
    buildDev
